=== monkeynaleo/warmux/trunk/data/authors.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT authors (team,contributors,thanks)>
<!ELEMENT team (sections+)>
<!ELEMENT contributors (sections+)>
<!ELEMENT thanks (sections+)>
<!ELEMENT section (author+)>
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT author (name,nickname?,email?,country?,description)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== monkeynaleo/warmux/trunk/data/authors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE authors SYSTEM "authors.dtd">

<authors>

<team>
	<section title="Active Team">
		<author><nickname>deki</nickname><name>Reiner HERRMANN</name><description>Programmer</description><website>http://www.reiner-h.de/</website><email>reiner_AT_reiner-h_DOT_de</email><country>Germany</country></author>
		<author><nickname>drayan</nickname><name>Yannig PERRÉ</name><description>Programmer</description><website>http://jb.berland.free.fr/dotclear/index.php/</website><email>yannig.perre_AT_gmail_DOT_com</email><country>France</country></author>
		<author><nickname>gentildemon</nickname><name>Matthieu FERTRÉ</name><description>Programmer</description><website>http://matthieu.fertre.free.fr/</website><email>matthieu.fertre_AT_free_DOT_fr</email><country>France</country></author>
		<author><nickname>haypo</nickname><name>Victor STINNER</name><description>Programmer and webmaster</description><website>http://www.haypocalc.com/</website><email>victor.stinner_AT_haypocalc_DOT_com</email><country>France</country></author>
		<author><nickname>lodesi</nickname><name>Laurent DEFERT SIMONNEAU</name><description>Programmer and graphic artist</description><email>lodesi2_AT_yahoo_DOT_fr</email><country>France</country></author>
		<author><nickname>OznOg</nickname><name>Sébastien GONZALVE</name><description>Programmer</description><website>http://zarb.org/%7Eoznog/</website><email>oznog_AT_zarb_DOT_org</email><country>France</country></author>
		<author><nickname>yeKcim</nickname><name>Anthony CARRÉ</name><description>Graphic artist</description><website>http://yeknan.free.fr/</website><email>yeknan_AT_yahoo_DOT_fr</email><country>France</country></author>
	</section>
	<section title="Inactive Team">
		<author><nickname>jcduberga</nickname><name>Jean-Christophe DUBERGA</name><description>Programmer</description><email>jcduberga_AT_gmx_DOT_de</email><country>Germany</country></author>
		<author><nickname>lami</nickname><name>Lawrence AZZOUG</name><description>Initial programmer and graphic artist of the game</description><website>http://perso.wanadoo.fr/lami/</website><email>lami_AT_wormux_DOT_org</email><country>France</country></author>
		<author><nickname>otacaon</nickname><name>Olivier SERRES</name><description>Programmer</description><email>olivier.serres_AT_gmail_DOT_com</email><country>France</country></author>
		<author><nickname>renaud</nickname><name>Renaud LOTTIAUX</name><description>Programmer</description><email>renaud.lottiaux_AT_free_DOT_fr</email><country>France</country></author>
	</section>
</team>

<contributors>
	<section title="Translations">
		<author><nickname>Alexandre</nickname><name>Alexandre PROKOUDINE</name><description>Translate Wormux into Russian</description><email>alexandre.prokoudine_AT_gmail_DOT_com</email><country>Russia</country></author>
		<author><nickname>Axel</nickname><name>Axel ROUSSEAU</name><description>Translate Wormux 0.8 in Esperanto</description><email>axel584_AT_axel584_DOT_org</email><country>France</country></author>
		<author><nickname>basse</nickname><name>Bastian SALMELA</name><description>Translate Wormux 0.7 in Finnish</description><email>asse_AT_kulma_DOT_org</email><country>Finland</country></author>
		<author><nickname>Binky</nickname><name>Antonio ACIÉN</name><description>Translate the website in Spanish</description><country>Spain</country></author>
		<author><nickname>Bruno</nickname><name>Bruno PIRES</name><description>First Portuguese version of Wormux</description><email>bruno.pires_AT_utbm_DOT_fr</email><country>France</country></author>
		<author><nickname>LnxSlck</nickname><name>Bruno QUEIRÓS</name><description>Translate Wormux 0.7.3 in Portuguese</description><email>brunomiguelqueiros_AT_gmail_DOT_com</email><country>Portugal</country></author>
		<author><nickname>Christian</nickname><name>Christian LOMSDALEN</name><description>Translated Wormux 0.8 to Norwegian</description><email>christian_AT_vindstille_DOT_net</email><country>Norway</country></author>
		<author><nickname>Daniel</nickname><name>Daniel NYLANDER</name><description>Translated Wormux 0.8 to Swedish</description><email>po_AT_danielnylander_DOT_se</email><country>Sweden</country></author>
		<author><nickname>Danny</nickname><name>Danny ALLEN</name><description>English translation of Wormux</description><email>dannya40uk_AT_yahoo.co_DOT_uk</email><country>England</country></author>
		<author><nickname>Eddy</nickname><name>Eddy PETRIŞOR </name><description>Translate Wormux in Romanian</description><email>eddy.petrisor_AT_gmail_DOT_com</email><country>Romania</country></author>
		<author><nickname>Frank</nickname><name>Frank VAN DER LOO</name><description>First Dutch version of Wormux</description><email>frank_l_AT_linuxmail_DOT_org</email><country>Netherlands</country></author>
		<author><nickname>Furkan</nickname><name>Furkan DUMAN</name><description>Wormux in Turkish</description><email>coderlord_AT_gmail_DOT_com</email></author>
		<author><nickname>gabó</nickname><name>Török GÁBOR</name><description>First Hungarian version of Wormux</description><email>gabo_AT_linuxportal_DOT_hu</email><country>Hungary</country></author>
		<author><nickname>Gaia</nickname><name>Gaia QUERO</name><description>Updated Italian translation</description><website>http://www.abctrad.com/</website><email>gaiaquero_AT_yahoo_DOT_fr</email><country>Italia</country></author>
		<author><nickname>Henrik</nickname><name>Henrik GEBAUER</name><description>Translated the whole website into German</description><email>henrik.gebauer_AT_web_DOT_de</email><country>Germany</country></author>
		<author><nickname>Janus</nickname><name>Janus TROELSEN</name><description>Translate Wormux in Danish</description><email>sangkok_AT_gmail_DOT_com</email><country>Denmark</country></author>
		<author><nickname>lux</nickname><name>Luciano FERRARO</name><description>Translate Wormux 0.7 in Italian</description><email>rebelcoders_AT_gmail_DOT_com</email><country>Italy</country></author>
		<author><nickname>Marc</nickname><name>Marc LANCTOT</name><description>First English version of INSTALL.en.txt</description><email>marc.lanctot_AT_mail.mcgill_DOT_ca</email><country>Canada</country></author>
		<author><nickname>Martin</nickname><name>Martin VOJČÍK</name><description>Slovak translation of Wormux</description><email>stryco_AT_centrum_DOT_sk</email><country>Russia</country></author>
		<author><nickname>Nicolas</nickname><name>Nicolas LETAVENIER</name><description>Help for English translation of the website</description><email>nicolas.letavenier_AT_utbm_DOT_fr</email><country>France</country></author>
		<author><nickname>Packo</nickname><name>Packo ASSAMITA</name><description>Translate the whole website in Spanish</description><email>packo_assamita_AT_supercable_DOT_es</email><country>Spain</country></author>
		<author><nickname>Pohodin</nickname><name>Pohodin ALEXANDER</name><description>Translated website to Russian</description><email>admin_AT_tuxgames_DOT_ru</email><country>Russia</country></author>
		<author><nickname>Rômulo</nickname><name>Rômulo FERNANDES</name><description>Translated Wormux to Brazilian/Portuguese</description><email>razor85_AT_users.sourceforge_DOT_net</email><country>Brazil</country></author>
		<author><nickname>Stefan</nickname><name>Stefan MARTENS</name><description>German translation</description><email>info_AT_stefan1200_DOT_de</email><country>Germany</country></author>
		<author><nickname>templer</nickname><name>Eduard BERMEJO</name><description>Add Spain AND Catalan translation in Wormux</description><email>templer_AT_iespana_DOT_es</email><country>Spain</country></author>
		<author><nickname>willy</nickname><name>Paolo NICORELLI</name><description>First Italian version of Wormux</description><email>p.nicorelli_AT_fastwebnet_DOT_it</email><country>Italy</country></author>
	</section>
		<section title="Package maintainers">
		<author><nickname>artefact</nickname><name>Jean PARPAILLON</name><description>Debian GNU/Linux and Ubuntu packages of Wormux 0.7. Also: Some scripts</description><website>http://transsib.free.fr/</website><email>jean.parpaillon_AT_free_DOT_fr</email><country>France</country></author>
		<author><nickname>che</nickname><name>Rudolf KASTL</name><description>Prepare RPM packages for Fedora Core 3</description><email>che666_AT_uni_DOT_de</email><country>Germany</country></author>
		<author><nickname>daja77</nickname><name>Daniel JAHRE</name><description>Package Wormux for RockLinux</description><email>daja_AT_rocklinux_DOT_org</email><country>Germany</country></author>
		<author><nickname>Emily</nickname><name>Emily BRANTLEY</name><description>Wormux 0.7beta2 package for Fedora Core 4</description><email>koneko.em_AT_gmail_DOT_com</email><country>United States</country></author>
		<author><nickname>fEnIo</nickname><name>Bartosz FENSKI</name><description>Debian package of Clanlib and Wormux prior to 0.7. Also: first Polish version of Wormux</description><website>http://skawina.eu.org/</website><email>fenio_AT_debian_DOT_org</email><country>Poland</country></author>
		<author><nickname>Julien</nickname><name>Julien CATALANO</name><description>Prepare RPM packages for Mandrake</description><email>julien.catalano_AT_gmail_DOT_com</email><country>France</country></author>
		<author><nickname>Kurosu</nickname><name>John DOE</name><description>Make Win32 port</description><email>kurosu_AT_free_DOT_fr</email><country>France</country></author>
		<author><nickname>Miwi</nickname><name>Martin Wilke</name><description>Made FreeBSD package</description><website>http://unixfreunde.de/</website><email>miwi_AT_FreeBSD_DOT_org</email></author>
		<author><nickname>Serge</nickname><name>Serge CLAUS</name><description>Wormux 0.7.4 package for Ubuntu Dapper</description><website>http://serge.claus.free.fr/</website><email>serge.claus_AT_free_DOT_fr</email><country>France</country></author>
	</section>
	<section title="Patches / Code">
