=== monkeynaleo/warmux/trunk/data/map/map.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (author,surface+,name,water,nb_mine,is_open,infinite_background) >
<!ELEMENT section (author+)>
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT author (name,nickname,email,country)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT surface EMPTY>
<!ATTLIST surface name CDATA #REQUIRED file CDATA #REQUIRED>

<!ELEMENT water (#PCDATA)>
<!ELEMENT nb_mine (#PCDATA)>
<!ELEMENT is_open (#PCDATA)>
<!ELEMENT infinite_background (#PCDATA)>

=== monkeynaleo/warmux/tags/wormux-0.8beta3/data/map/qingqong/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Anthony CARRÃ‰ and Olivier Boyer</name>
    <nickname>yeKcim and Zi Olive</nickname>
    <email>yeknan AT yahoo DOT fr</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="qingqong.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Qing-Qong</name>
  <water>0</water>
  <nb_mine>5</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="1000" y="500" />
  <point name="lower_right_pad" x="1000" y="0" />

</resources>

=== monkeynaleo/warmux/branches/wormux-0.7.9/data/map/island/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Anthony CARRÃ‰</name>
    <nickname>yeKcim</nickname>
    <email>yeknan AT yahoo DOT fr</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="island.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Island</name>
  <water>1</water>
  <nb_mine>5</nb_mine>
  <is_open>1</is_open>

</resources>

=== monkeynaleo/warmux/trunk/data/map/crystal/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>C. Schalkwijk</name>
    <nickname>Papa.Coen</nickname>
    <email>Papa.Coen@gmail.com</email>
    <country>The Netherlands</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="crystal.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Crystal</name>
  <water>1</water>
  <nb_mine>3</nb_mine>
  <is_open>1</is_open>
</resources>

=== monkeynaleo/warmux/trunk/data/map/goodandevil/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Anthony CARRÃ‰</name>
    <nickname>yeKcim</nickname>
    <email>yeknan AT yahoo DOT fr</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="goodandevil.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Good and Evil</name>
  <water>0</water>
  <nb_mine>5</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="1000" y="1000" />
  <point name="lower_right_pad" x="1000" y="0" />

</resources>

=== monkeynaleo/warmux/tags/wormux-0.8beta2/data/map/battlenight/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Glenn ROLLAND</name>
    <nickname>Glenux</nickname>
    <email>glenux AT gmail.com</email>
    <country>France</country>
  </author>

  <surface name="sky" file="battlenight-bg.jpg" />
  <surface name="map" file="battlenight-fg.png" />
  <surface name="preview" file="battlenight-all.jpg" />

  <name>Battle Night</name>
  <water>0</water>
  <nb_mine>3</nb_mine>
  <is_open>1</is_open>
</resources>

=== monkeynaleo/warmux/branches/fixedpoint/data/map/chess/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Lawrence AZZOUG</name>
    <nickname>Lami</nickname>
    <email>lami AT wormux.org</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" /> 

  <sky_layer>2</sky_layer>
  <surface name="sky_layer_0" file="sky0.png" />
  <surface name="sky_layer_1" file="sky1.png" />
  <surface name="map"     file="map.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Chess</name>
  <water>water</water>
  <nb_mine>3</nb_mine>
  <nb_barrel>1</nb_barrel>
  <is_open>1</is_open>

</resources>

=== monkeynaleo/warmux/branches/wormux-0.8beta1/data/map/paradis/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
	<author>
		<name>Olivier Boyer</name>
		<nickname>ziolive</nickname>
		<email>ziolive AT gmail.com</email>
		<country>France</country>
	</author>

	<surface name="sky" file="decor_paradis_BG.jpg" />
	<surface name="map" file="decor_paradis.png" />
	<surface name="preview" file="paradis_preview.jpg" />


	<name>Paradis</name>
	<water>0</water>
	<nb_mine>7</nb_mine>
	<is_open>1</is_open>

	<music_playlist>sea</music_playlist>
</resources>
