=== monkeynaleo/warmux/trunk/data/body/body.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (authos, sprite+, clothe, movement+)>

<!-- Author part -->
<!ELEMENT author (name,nickname?,email,country)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!-- sprite -->
<!ELEMENT sprite (image, anchor?, (attached+)? )>
<!ATTLIST sprite name CDATA #REQUIRED type CDATA #REQUIRED>

<!ELEMENT image (grid?)>
<!ATTLIST image file CDATA #REQUIRED>
<!ELEMENT grid EMPTY>
<!ATTLIST grid pos CDATA #REQUIRED size CDATA #REQUIRED array CDATA #REQUIRED>

<!ELEMENT anchor EMPTY>
<!ATTLIST anchor dx CDATA #REQUIRED dy CDATA #REQUIRED>

<!ELEMENT attached EMPTY>
<!ATTLIST attached member_type CDATA #REQUIRED frame CDATA #REQUIRED dx CDATA #REQUIRED dy CDATA #REQUIRED>

<!-- clothe -->
<!ELEMENT clothe (member+)>
<!ATTLIST clothe name CDATA #FIXED "normal">

<!-- movement -->
<!ELEMENT movement (collision_rect, frame+)>
<!ATTLIST movement name CDATA #REQUIRED speed CDATA #REQUIRED>

<!ELEMENT collision_rect EMPTY>
<!ATTLIST collision_rect left CDATA #REQUIRED right CDATA #REQUIRED top CDATA #REQUIRED bottom CDATA #REQUIRED>

<!ELEMENT frame (member+)>
<!ATTLIST frame number CDATA #REQUIRED>

<!ELEMENT member EMPTY>
<!ATTLIST member
          name CDATA #IMPLIED
          layer CDATA #IMPLIED
          type CDATA #IMPLIED
          dx CDATA #IMPLIED
          dy CDATA #IMPLIED
          angle CDATA #IMPLIED
          follow_crosshair CDATA #IMPLIED
          follow_speed CDATA #IMPLIED
          follow_direction CDATA #IMPLIED>

=== monkeynaleo/warmux/trunk/data/body/konqiteam/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../body.dtd" []>
<resources>

<!--   ###########################################
       ###############             ###############
       ##############    AUTHOR     ##############
       ###############             ###############
       ###########################################   -->

<author>
  <name>yeKcim</name>
  <email>yekcim AT crocobox.org</email>
</author>








<!--   ###########################################
       ###############             ###############
       ##############     ALIAS     ##############
       ###############             ###############
       ###########################################   -->

<alias movement="weapon-riot_bomb-begin-shoot" correspond_to="weapon-bazooka-begin-shoot" />
<alias movement="weapon-riot_bomb-end-shoot" correspond_to="weapon-bazooka-end-shoot" />
<alias movement="weapon-bazooka-select" correspond_to="weapon-bazooka-begin-shoot" />
<alias movement="weapon-riot_bomb-select" correspond_to="weapon-bazooka-begin-shoot" />
<alias movement="weapon-automatic_bazooka-select" correspond_to="weapon-bazooka-begin-shoot" />
<alias movement="weapon-automatic_bazooka-begin-shoot" correspond_to="weapon-bazooka-begin-shoot" />
<alias movement="weapon-automatic_bazooka-end-shoot" correspond_to="weapon-bazooka-end-shoot" />
<alias movement="weapon-cluster_bomb-begin-shoot" correspond_to="weapon-grenade-begin-shoot" />
<alias movement="weapon-cluster_bomb-end-shoot" correspond_to="weapon-grenade-end-shoot" />
<alias movement="weapon-holly_grenade-begin-shoot" correspond_to="weapon-grenade-begin-shoot" />
<alias movement="weapon-holly_grenade-end-shoot" correspond_to="weapon-grenade-end-shoot" />
<alias movement="weapon-snipe_rifle-begin-shoot" correspond_to="weapon-uzi-begin-shoot" />
<alias movement="weapon-snipe_rifle-end-shoot" correspond_to="weapon-uzi-end-shoot" />
<alias movement="weapon-gnulauncher-begin-shoot" correspond_to="weapon-tux-begin-shoot" />
<alias movement="weapon-gnulauncher-end-shoot" correspond_to="weapon-tux-end-shoot" />







<!--   ###########################################
       ###############             ###############
       ##############   SKELETON    ##############
       ###############             ###############
       ###########################################   -->

<!-- ###### Body ###### -->
<sprite name="body-normal" type="body">
	<image file="body.png"/>
	<anchor dx="16" dy="17"/>
	<attached member_type="head" frame="*" dx="12" dy="5"/>
	<attached member_type="arm-right" frame="*" dx="3" dy="18"/>
	<attached member_type="arm2" frame="*" dx="3" dy="18"/>
	<attached member_type="arm-left" frame="*" dx="8" dy="17"/>
	<attached member_type="foot-left" frame="*" dx="10" dy="29"/>
	<attached member_type="foot-right" frame="*" dx="5" dy="30"/>
	<attached member_type="tail" frame="*" dx="2" dy="38"/>
	<attached member_type="wing-right" frame="*" dx="2" dy="23"/>
	<attached member_type="wing-left" frame="*" dx="5" dy="22"/>
	<attached member_type="construct" frame="*" dx="7" dy="6"/>
</sprite>

<sprite name="tail" type="tail">
	<image file="tail.png"/>
	<anchor dx="12" dy="13"/>
</sprite>

<!-- ###### Head ###### -->
<sprite name="head" type="head">
	<image file="eyes.png"/>
	<anchor dx="2" dy="2"/>
	<attached member_type="horns" frame="*" dx="-2" dy="-2"/>
	<attached member_type="nose" frame="*" dx="4" dy="9"/>
	<attached member_type="helmet" frame="*" dx="0" dy="3"/>
</sprite>

<sprite name="horns" type="horns">
	<image file="horns.png"/>
	<anchor dx="3" dy="6"/>
</sprite>

<sprite name="nose" type="nose">
	<image file="nose.png"/>
	<anchor dx="3" dy="7"/>
</sprite>


<!-- ###### Arms ###### -->
<sprite name="arm-left" type="arm-left">
	<image file="arm1.png"/>
	<anchor dx="3" dy="0"/>
</sprite>

<sprite name="arm-right" type="arm-right">
	<image file="arm1.png"/>
	<anchor dx="3" dy="0"/>
	<attached member_type="weapon" frame="*" dx="7" dy="7"/>

</sprite>

<sprite name="arm2" type="arm2">
	<image file="arm2.png"/>
	<anchor dx="0" dy="1"/>
	<attached member_type="yoyo" frame="*" dx="16" dy="8"/>
</sprite>


<!-- ###### Legs ###### -->
<sprite name="foot-left" type="foot-left">
	<image file="foot-left.png"/>
	<anchor dx="2" dy="0"/>
</sprite>

<sprite name="foot-right" type="foot-right">
	<image file="foot-right.png"/>
	<anchor dx="2" dy="0"/>
</sprite>

<!-- ###### Wings ###### -->
<sprite name="wing-right" type="wing-right">
	<image file="wing.png"/>
	<anchor dx="15" dy="10"/>
</sprite>

<sprite name="wing-left" type="wing-left">
	<image file="wing.png"/>
	<anchor dx="15" dy="10"/>
</sprite>

<!-- ###### Helmet ###### -->
<sprite name="helmet" type="helmet">
	<image file="helmet.png"/>
	<anchor dx="9" dy="13"/>
</sprite>

<!-- ###### Yoyo ###### -->
<sprite name="yoyo" type="yoyo" go_through_ground="true">
	<image file="yoyo.png">
		<grid pos="0,0" size="32,42" array="36,1"/>
	</image>
	<anchor dx="29" dy="0"/>
	<animation speed="150"/>
</sprite>

<!-- ###### Dead ###### -->
<sprite name="body-dead" type="body">
	<image file="dead.png">
		<grid pos="0,0" size="27,31" array="6,1"/>
	</image>
	<anchor dx="0" dy="0"/>
	<animation speed="150"/>
</sprite>


<!-- ###### Black ###### -->
<sprite name="body-black" type="body">
	<image file="black.png"/>
	<anchor dx="12" dy="15"/>
</sprite>

<!-- ###### Construct ###### -->
<sprite name="construct" type="construct" >
	<image file="c1.png"/>
	<anchor dx="7" dy="12"/>
	<attached member_type="c2" frame="*" dx="1" dy="8" />
</sprite>

<sprite name="c2" type="c2" >
	<image file="c2.png"/>
	<anchor dx="0" dy="0"/>
</sprite>







<!--   ###########################################
       ###############             ###############
       ##############    CLOTHES    ##############
       ###############             ###############
       ###########################################   -->

<!-- ###### Normal ###### -->
<clothe name="normal">
	<member name="wing-left" layer="0"/>
	<member name="tail" layer="1"/>
	<member name="wing-right" layer="2"/>
	<member name="arm-left" layer="3"/>
	<member name="foot-left" layer="4"/>
	<member name="body-normal" layer="5"/>
	<member name="horns" layer="6"/>
	<member name="head" layer="7"/>
	<member name="nose" layer="8"/>
	<member name="foot-right" layer="9"/>
	<member name="arm-right" layer="10"/>
	<member name="weapon" layer="11"/>
</clothe>

<!-- ###### Jetpack ###### -->
<clothe name="jetpack"> <!-- When jetpack weapon is selected, during walk, jump movement... -->
	<member name="wing-left" layer="0"/>
	<member name="tail" layer="1"/>
	<member name="wing-right" layer="2"/>
	<member name="arm-left" layer="3"/>
	<member name="foot-left" layer="4"/>
	<member name="body-normal" layer="5"/>
	<member name="horns" layer="6"/>
	<member name="head" layer="7"/>
	<member name="nose" layer="8"/>
	<member name="foot-right" layer="9"/>
	<member name="arm-right" layer="10"/>
</clothe>

<clothe name="jetpack-fire"> <!-- When jetpack weapon is selected and used -->
	<member name="wing-left" layer="0"/>
	<member name="tail" layer="1"/>
	<member name="wing-right" layer="2"/>
	<member name="arm-left" layer="3"/>
	<member name="foot-left" layer="4"/>
	<member name="body-normal" layer="5"/>
	<member name="horns" layer="6"/>
	<member name="head" layer="7"/>
	<member name="nose" layer="8"/>
	<member name="foot-right" layer="9"/>
	<member name="arm-right" layer="10"/>
</clothe>

<!-- # Construct/Airhammer helmet # -->
<clothe name="weapon-construct">
	<member name="wing-left" layer="0"/>
	<member name="tail" layer="1"/>
	<member name="wing-right" layer="2"/>
	<member name="arm-left" layer="3"/>
	<member name="foot-left" layer="4"/>
	<member name="c2" layer="5"/>
	<member name="body-normal" layer="6"/>
	<member name="head" layer="7"/>
	<member name="nose" layer="8"/>
	<member name="construct" layer="9"/>
	<member name="foot-right" layer="10"/>
	<member name="arm-right" layer="11"/>
	<member name="weapon" layer="12"/>
</clothe>

<clothe name="weapon-airhammer">
	<member name="wing-left" layer="0"/>
	<member name="tail" layer="1"/>
	<member name="wing-right" layer="2"/>
	<member name="arm-left" layer="3"/>
	<member name="foot-left" layer="4"/>
	<member name="c2" layer="5"/>
	<member name="body-normal" layer="6"/>
	<member name="head" layer="7"/>
	<member name="nose" layer="8"/>
	<member name="construct" layer="9"/>
	<member name="foot-right" layer="10"/>
	<member name="arm-right" layer="11"/>
	<member name="weapon" layer="12"/>
</clothe>

<!-- ###### Helmet ###### -->
<clothe name="helmet">
	<member name="wing-left" layer="0"/>
	<member name="tail" layer="1"/>
	<member name="wing-right" layer="2"/>
	<member name="arm-left" layer="3"/>
	<member name="foot-left" layer="4"/>
	<member name="body-normal" layer="5"/>
	<member name="horns" layer="6"/>
	<member name="head" layer="7"/>
	<member name="nose" layer="8"/>
	<member name="foot-right" layer="9"/>
	<member name="arm-right" layer="10"/>
	<member name="helmet" layer="11"/>
</clothe>

<!-- ###### Animation Yoyo ###### -->
<clothe name="animation0">
	<member name="wing-left" layer="0"/>
	<member name="tail" layer="1"/>
	<member name="wing-right" layer="2"/>
	<member name="arm-left" layer="3"/>
	<member name="foot-left" layer="4"/>
	<member name="body-normal" layer="5"/>
	<member name="horns" layer="6"/>
	<member name="head" layer="7"/>
	<member name="nose" layer="8"/>
	<member name="foot-right" layer="9"/>
	<member name="arm2" layer="10"/>
	<member name="yoyo" layer="11"/>
</clothe>

<!-- ###### Animation Tired ###### -->
<clothe name="animation1">
	<member name="wing-left" layer="0"/>
	<member name="tail" layer="1"/>
	<member name="wing-right" layer="2"/>
	<member name="arm-left" layer="3"/>
